### ISSUE TITLE
Limit to Number of Albums to Download?

### ISSUE THREAD

**Issue by ajsnyde** [jsavargas/zspotify#39]
Hi! I'd like to download an entire artist's discography but am running into an issue where it stops around 20 albums in. Running via the Docker image using a link to artist:
https://open.spotify.com/artist/2aaLAng2L2aWD2FClzwiep?si=OjA40YyrSZKNIQArZhmO6Q
![image](https://user-images.githubusercontent.com/11302823/197082705-f12653b9-be89-4637-90de-c87fd860e6c3.png)
For some reason, it just stops at 2013 (right as I was getting to their good stuff!). I've tried re-running with it stopping at the same location. Is there some configuration issue? They have a few dozen more albums, is there a way to get the rest?

**Comment by jsavargas** [comment]
Thanks for sharing the url, I will do tests with that same url and find where the error is.

**Comment by EDad-v2** [comment]
I was goofing around with the URL and got the exact results. It exited at the end of the very same album.  I tried this twice, same results.

Then I launched Zspotify with no arguments
Entered: Dream Theater, then selected 151 for the artist.  It downloaded all of the albums without issue.  Roughly 4.5 GB

Debian Bullseye, no Docker container.

**Comment by EDad-v2** [comment]
I got to the bottom of this and you were correct. There was a 20 album limit although I'm certain the limit was not intentional. Now the function grabs them all :)
Pull request here: https://github.com/jsavargas/zspotify/pull/55/commits/6f8f94eea9910d21c14e65090f2c255789944d36

![zspotify-get_artist_albums](https://user-images.githubusercontent.com/91480349/204690276-2ea6aab0-6f20-45a5-8bdd-e5539d0eadc7.png)

In the code a limit of 50 is shown, but it collects 50 and loops to grab more until it's got all the artist has.  Frank Zappa's url will grab you more than 160 albums :open_mouth:

**Comment by mwwdh** [comment]
Sorry to bring this up but i have this exact same problem. It doesn't matter if i start via url (-ar *) or search inside zspotify. It only select 50 items.
